apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-camunda-8
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/j-lindner/argocd2024.git
    path: charts/my-camunda-8/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
