global:
  image:
    tag: 8.5.0
  identity:
    auth:
      enabled: false

camunda-platform:
  console:
    enabled: false

  identity:
    enabled: false

  tasklist:
    enabled: true

  optimize:
    enabled: false

  connectors:
    enabled: false

  # Reduce for Zeebe and Gateway the configured replicas and with that the required resources
  # to get it running locally
  zeebe:
    clusterSize: 1
    partitionCount: 1
    replicationFactor: 1
    # Request smaller persistent volumes.
    pvcSize: 10Gi

  zeebeGateway:
    replicas: 1

  elasticsearch:
    master:
      replicaCount: 1
      # Request smaller persistent volumes.
      persistence:
        size: 15Gi